---
- name: Manage OS-specific dependencies.
  include: "dependencies_{{ ansible_os_family }}.yml"

- name: Download the ruby source in /usr/local/src if not yet present
  get_url:
    url: https://cache.ruby-lang.org/pub/ruby/{{ ruby_major_minor }}/ruby-{{ ruby_version }}.tar.bz2
    dest: /usr/local/src/ruby-{{ ruby_version }}.tar.bz2
    checksum: "{{ ruby_version_checksum }}"

- name: Upload the ruby install script
  template: src=ruby-install.j2 dest=/usr/local/src/ruby-{{ ruby_version }}-install.sh owner=root group=root mode=0755

- name: Configure gems so that docs are not generated
  copy: src=gemrc dest=/etc/gemrc owner=root group=root mode=0644

- name: Install ruby version {{ ruby_version }} from source
  command: /usr/local/src/ruby-{{ ruby_version }}-install.sh creates=/usr/local/src/ruby-{{ ruby_version }}/ruby
  become: yes

- name: Install core gems
  gem:
    state: present
    user_install: no
    executable: /usr/local/bin/gem
    name: "{{ item }}"
  with_items:
    - rubygems-update
    - bundler

- name: Update rubygems
  command: /usr/local/bin/gem update --system
